const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const dbUrl=process.env.TEST_DATABASE_URL;
if(!dbUrl || !['127.0.0.1','localhost'].includes(new URL(dbUrl).hostname) || !/scalpeldiary_(test|restore)/.test(new URL(dbUrl).pathname)) throw new Error('TEST_DATABASE_URL must identify an isolated local scalpeldiary_test or scalpeldiary_restore database');
process.env.DATABASE_URL=dbUrl;process.env.JWT_SECRET='synthetic-integration-test-secret';process.env.NODE_ENV='test';delete process.env.VAPID_PRIVATE_KEY;delete process.env.VAPID_PUBLIC_KEY;
const db=require('../dist/database/db').default;const app=require('../dist/app').default;const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');
let server,base;const ids={resident:randomUUID(),other:randomUUID(),supervisor:randomUUID(),master:randomUUID()};const years={resident:randomUUID(),other:randomUUID()};const tokens={};let rated, pending, log,assignment,category;
async function request(method,url,body,who='resident') {const response=await fetch(base+'/api'+url,{method,headers:{Authorization:'Bearer '+tokens[who],'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json()}catch{data={}}return {status:response.status,data};}
before(async()=>{await db.query("INSERT INTO academic_years(year_name,start_month,start_year,is_active) SELECT 'Synthetic test year',7,2099,true WHERE NOT EXISTS(SELECT 1 FROM academic_years WHERE is_active)");const password=await bcrypt.hash('FixturePassword123',4);for(const [role,id]of Object.entries(ids)){await db.query('INSERT INTO users(id,email,name,password,role,is_chief_resident) VALUES($1,$2,$3,$4,$5,$6)',[id,id+'@example.invalid','Synthetic '+role,password,role==='other'?'RESIDENT':role.toUpperCase(),role==='resident']);tokens[role]=jwt.sign({id,role:role.toUpperCase(),version:0},process.env.JWT_SECRET);}
for(const role of ['resident','other'])await db.query('INSERT INTO resident_years(id,resident_id,year) VALUES($1,$2,1)',[years[role],ids[role]]);
log=(await db.query("INSERT INTO surgical_logs(resident_id,year_id,date,mrn,age,sex,diagnosis,procedure,procedure_type,procedure_category,place_of_practice,surgery_role,supervisor_id,status,rating,anonymous_comment) VALUES($1,$2,'2026-10-07','SYNTHETIC',30,'MALE','Synthetic','Synthetic','ELECTIVE','Minor Surgery','Y12HMC','PRIMARY_SURGEON',$3,'RATED',80,'PRIVATE SYNTHETIC') RETURNING id",[ids.resident,years.resident,ids.supervisor])).rows[0].id;
for(const status of ['RATED','PENDING']){const id=(await db.query("INSERT INTO presentations(resident_id,year_id,date,title,venue,presentation_type,supervisor_id,status) VALUES($1,$2,'2026-10-07','Synthetic','Y12HMC','SEMINAR',$3,$4) RETURNING id",[ids.resident,years.resident,ids.supervisor,status])).rows[0].id;if(status==='RATED')rated=id;else pending=id;}
assignment=(await db.query("INSERT INTO presentation_assignments(title,presentation_type,presenter_id,moderator_id,created_by,status) VALUES('Synthetic','SEMINAR',$1,$2,$2,'assigned') RETURNING id",[ids.resident,ids.supervisor])).rows[0].id;
category=(await db.query("INSERT INTO duty_categories(name,color) VALUES($1,'#123456') RETURNING id",['Synthetic '+randomUUID()])).rows[0].id;
server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{if(server)await new Promise(r=>server.close(r));await db.end();});
test('resident cannot read another resident’s records or author supervisory comments',async()=>{for(const url of ['/logs/resident/'+ids.other,'/presentations/resident/'+ids.other,'/general-comments/resident/'+ids.other,'/analytics/dashboard?residentId='+ids.other,'/analytics/resident?residentId='+ids.other,'/users/resident-years/'+ids.other])assert.equal((await request('GET',url)).status,403,url);assert.equal((await request('POST','/general-comments',{residentId:ids.other,comment:'Synthetic'})).status,403);});
test('own records expose labels and omit anonymous feedback; assigned supervisor retains exact score',async()=>{const own=await request('GET','/logs/my-logs?yearId='+years.resident);assert.equal(own.status,200);const record=own.data.find(x=>x.id===log);assert.equal(record.rating,'Good');assert.ok(!('anonymous_comment'in record));const sup=await request('GET','/logs/rated',undefined,'supervisor');assert.equal(sup.data.find(x=>x.id===log).rating,80);});
test('rated presentation cannot be edited or deleted; pending one can be updated',async()=>{assert.equal((await request('PUT','/presentations/'+rated,{title:'Changed'})).status,400);assert.equal((await request('DELETE','/presentations/'+rated)).status,400);assert.equal((await request('PUT','/presentations/'+pending,{title:'Updated synthetic',date:'2026-10-07',venue:'Y12HMC',presentationType:'SEMINAR',supervisorId:ids.supervisor})).status,200);});
test('promotion preserves historical records and cannot move backwards',async()=>{assert.equal((await request('PUT','/users/'+ids.resident+'/year',{newYear:2},'master')).status,200);assert.equal((await db.query('SELECT count(*) FROM surgical_logs WHERE id=$1',[log])).rows[0].count,'1');assert.equal((await db.query('SELECT count(*) FROM resident_years WHERE resident_id=$1',[ids.resident])).rows[0].count,'2');assert.equal((await request('PUT','/users/'+ids.resident+'/year',{newYear:1},'master')).status,400);});
test('assignment completion is idempotent even under concurrent requests',async()=>{const attempts=await Promise.all([1,2].map(()=>request('POST','/presentation-assignments/'+assignment+'/mark-presented',{yearId:years.resident,presented_date:'2026-10-07'})));assert.deepEqual(attempts.map(x=>x.status),[200,200]);assert.equal(attempts[0].data.presentation.id,attempts[1].data.presentation.id);const row=(await db.query('SELECT presentation_id,presented_date FROM presentation_assignments WHERE id=$1',[assignment])).rows[0];assert.ok(row.presentation_id);assert.ok(row.presented_date);});
test('creation rejects another resident’s year',async()=>{assert.equal((await request('POST','/presentations',{yearId:years.other,date:'2026-10-07',title:'Synthetic'})).status,400);});
function logBody(){return {yearId:years.resident,date:'2026-10-07',mrn:'SYNTHETIC',age:30,sex:'MALE',diagnosis:'Synthetic',procedure:'Synthetic',procedureType:'ELECTIVE',procedureCategory:'Minor Surgery',placeOfPractice:'Y12HMC',surgeryRole:'PRIMARY_SURGEON',supervisorId:ids.supervisor};}
test('batch creation rolls back partial writes and retries are idempotent',async()=>{const before=(await db.query('SELECT count(*) FROM surgical_logs WHERE resident_id=$1',[ids.resident])).rows[0].count;const bad={...logBody(),supervisorId:ids.resident};assert.equal((await request('POST','/logs/batch',{requestKey:randomUUID(),records:[logBody(),bad]})).status,400);assert.equal((await db.query('SELECT count(*) FROM surgical_logs WHERE resident_id=$1',[ids.resident])).rows[0].count,before);const body={requestKey:randomUUID(),records:[logBody(),logBody()]};const first=await request('POST','/logs/batch',body);const retry=await request('POST','/logs/batch',body);assert.equal(first.status,201);assert.equal(retry.status,201);assert.deepEqual(first.data.map(x=>x.id),retry.data.map(x=>x.id));});
test('ratings accept zero, reject values outside range and reject SQL-shaped month',async()=>{assert.equal((await request('POST','/presentations/'+pending+'/rate',{rating:0},'supervisor')).status,200);assert.equal((await request('POST','/logs/'+log+'/rate',{rating:101},'supervisor')).status,400);assert.equal((await request('POST','/logs/detachment-verify',{residentId:ids.resident,detachmentType:'ALERT',month:"2026-01'",rating:80},'master')).status,400);});
test('day replacement is atomic when an assignment is invalid',async()=>{const good={assignments:[{resident_id:ids.resident,category_id:category}]};assert.equal((await request('PUT','/duties/day/2099-01-01',good)).status,200);assert.equal((await request('PUT','/duties/day/2099-01-01',{assignments:[{resident_id:ids.other,category_id:category},{resident_id:ids.master,category_id:category}]})).status,400);const rows=(await db.query("SELECT resident_id FROM monthly_duties WHERE duty_date='2099-01-01'")).rows;assert.deepEqual(rows.map(x=>x.resident_id),[ids.resident]);});
test('valid image within advertised limit succeeds; wrong format fails',async()=>{assert.equal((await request('POST','/users/profile-picture',{profilePicture:'data:image/png;base64,'+'A'.repeat(150000)})).status,200);assert.equal((await request('POST','/users/profile-picture',{profilePicture:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);});
test('category colors persist',async()=>{assert.equal((await request('PUT','/duties/categories/'+category,{color:'#abcdef'})).status,200);assert.equal((await db.query('SELECT color FROM duty_categories WHERE id=$1',[category])).rows[0].color,'#abcdef');});
test('role dashboards, schedules and analytics execute against the migrated schema',async()=>{
 const routes={resident:['/analytics/dashboard?yearId='+years.resident,'/analytics/resident?yearId='+years.resident,'/progress/year/'+years.resident,'/rotations/my-rotations','/rotations/','/duties/today','/duties/monthly/2026/10','/activities/today','/activities/monthly/2026/10','/presentation-assignments','/presentations/stats?yearId='+years.resident],supervisor:['/analytics/supervisor','/analytics/supervisor/residents','/analytics/supervisor/resident/'+ids.resident,'/logs/to-rate','/presentations/to-rate'],master:['/users','/rotations/academic-years','/logs/detachment-summary']};
 for(const [who,urls] of Object.entries(routes))for(const url of urls)assert.equal((await request('GET',url,undefined,who)).status,200,who+' '+url);
});
test('disabled push delivery retains a retryable outbox row',async()=>{
 const id=(await db.query("INSERT INTO notification_outbox(user_id,title,body) VALUES($1,'Synthetic','Synthetic') RETURNING id",[ids.resident])).rows[0].id;
 // Isolate the candidate from fixture notifications queued by preceding tests.
 await db.query("UPDATE notification_outbox SET next_attempt_at=now()+interval '1 day' WHERE id<>$1",[id]);
 await require('../dist/services/outbox').deliverOutbox();
 const row=(await db.query('SELECT sent_at,attempts FROM notification_outbox WHERE id=$1',[id])).rows[0];
 assert.equal(row.sent_at,null);assert.equal(row.attempts,1);
});
test('concurrent logins do not exhaust the transaction pool',{timeout:10000},async()=>{const replies=await Promise.all(Array.from({length:16},()=>request('POST','/auth/login',{email:ids.resident+'@example.invalid',password:'FixturePassword123'})));assert.ok(replies.every(x=>x.status===200));});
test('suspension blocks existing token and login; master cannot be suspended',async()=>{assert.equal((await request('PUT','/users/'+ids.other+'/suspend',{},'master')).status,200);assert.equal((await request('GET','/users/me',undefined,'other')).status,401);const login=await request('POST','/auth/login',{email:ids.other+'@example.invalid',password:'FixturePassword123'});assert.equal(login.status,401);assert.notEqual((await request('PUT','/users/'+ids.master+'/suspend',{},'master')).status,200);});
test('password reset revokes an already-issued token',async()=>{assert.equal((await request('POST','/users/reset-password/'+ids.other,{newPassword:'NewFixturePassword123'},'master')).status,200);await request('PUT','/users/'+ids.other+'/activate',{},'master');assert.equal((await request('GET','/users/me',undefined,'other')).status,401);});
test('supervisor and senior-resident surgery counts group MRN/date without losing individual ratings',async()=>{
 for(const who of ['supervisor','resident']) {
  const before=(await request('GET','/analytics/supervisor',undefined,who)).data;
  const prior=(await request('GET','/analytics/supervisor/resident/'+ids[who]+'?year=1',undefined,'master')).data.ratedLogs;
  const mrn='GROUP-'+randomUUID();
  const inserted=[];
  try {
   for(const [recordMrn,date,status,rating] of [[mrn,'2026-10-07','RATED',80],[mrn+' ','2026-10-07','RATED',0],[mrn,'2026-10-07','PENDING',null],[mrn,'2026-10-08','RATED',90],[mrn+'B','2026-10-07','RATED',70]]) {
    const row=await db.query("INSERT INTO surgical_logs(resident_id,year_id,date,mrn,age,sex,diagnosis,procedure,procedure_type,procedure_category,place_of_practice,surgery_role,supervisor_id,status,rating) VALUES($1,$2,$3,$4,30,'MALE','Synthetic','Different procedure','ELECTIVE','Minor Surgery','Y12HMC','ASSISTANT',$5,$6,$7) RETURNING id",[ids.other,years.other,date,recordMrn,ids[who],status,rating]);
    inserted.push(row.rows[0].id);
   }
   const result=(await request('GET','/analytics/supervisor',undefined,who)).data;
   assert.equal(result.uniqueProcedures-before.uniqueProcedures,3);
   assert.equal(result.totalSurgeries-before.totalSurgeries,3);
   assert.equal(result.totalResidentLogs-before.totalResidentLogs,5);
   assert.equal(result.pendingProcedures-before.pendingProcedures,1);
   const reviewed=(await request('GET','/analytics/supervisor/resident/'+ids[who]+'?year=1',undefined,'master')).data;
   if(who==='resident') assert.equal(reviewed.ratedLogs-prior,3);
   const rows=(await request('GET','/logs/rated',undefined,who)).data.filter(x=>inserted.includes(x.id));
   assert.equal(rows.length,4);
   assert.ok(rows.some(x=>x.rating===0));
  } finally {await db.query('DELETE FROM surgical_logs WHERE id=ANY($1::uuid[])',[inserted]);}
 }
});
test('deactivating supervisor preserves supervised records',async()=>{assert.equal((await request('DELETE','/users/'+ids.supervisor,undefined,'master')).status,200);assert.equal((await db.query('SELECT count(*) FROM surgical_logs WHERE id=$1',[log])).rows[0].count,'1');assert.equal((await request('GET','/users/me',undefined,'supervisor')).status,401);});
test('database enforces one active academic year and score bounds',async()=>{await assert.rejects(db.query("INSERT INTO academic_years(year_name,start_month,start_year,is_active) VALUES('Synthetic',7,2099,true)"),{code:'23505'});await assert.rejects(db.query('UPDATE surgical_logs SET rating=101 WHERE id=$1',[log]),{code:'23514'});});
test('readiness responds and HTTP migration surface is absent',async()=>{assert.equal((await fetch(base+'/ready')).status,200);assert.equal((await request('GET','/migrations')).status,404);});
